import { Editor, Project, ProjectCategory, ProjectStatus } from './types';
import { subDays, addDays } from 'date-fns';

export const initialEditors: Editor[] = [
  { id: '1', name: 'Harinder', rating: 4.5 },
  { id: '2', name: 'Tarun', rating: 4.8 },
  { id: '3', name: 'Gurwinder', rating: 4.2 },
  { id: '4', name: 'Roop', rating: 4.9 },
];

const now = new Date();

export const initialProjects: Project[] = [
  {
    id: 'PROJ-001',
    name: 'Sunset Wedding Photos',
    status: 'Done',
    editorId: '1',
    assignDate: subDays(now, 10),
    deadline: subDays(now, 5),
    completionDate: subDays(now, 6),
    notes: 'Client wants vibrant, warm tones. Focus on the golden hour shots.',
    idCaller: 'CLIENT-A',
    imageUrl: 'https://picsum.photos/seed/1/600/400',
    imageHint: 'wedding couple',
    category: 'Wedding',
    picturesEdited: 150,
  },
  {
    id: 'PROJ-002',
    name: 'Corporate Headshots',
    status: 'In Progress',
    editorId: '2',
    assignDate: subDays(now, 3),
    deadline: addDays(now, 2),
    completionDate: null,
    notes: 'Standard corporate headshots. Blue background. 10 employees.',
    idCaller: 'CLIENT-B',
    imageUrl: 'https://picsum.photos/seed/2/600/400',
    imageHint: 'business person',
    category: 'Corporate',
  },
  {
    id: 'PROJ-003',
    name: 'Real Estate Showcase',
    status: 'Assigned',
    editorId: '3',
    assignDate: subDays(now, 1),
    deadline: addDays(now, 5),
    completionDate: null,
    notes: 'Bright and airy style. Highlight the large windows and open spaces.',
    idCaller: 'CLIENT-C',
    imageUrl: 'https://picsum.photos/seed/3/600/400',
    imageHint: 'modern house',
    category: 'Real Estate',
  },
  {
    id: 'PROJ-004',
    name: 'New Product Launch',
    status: 'New',
    editorId: null,
    assignDate: null,
    deadline: addDays(now, 10),
    completionDate: null,
    notes: 'Clean, minimalist shots of the new gadget. White background.',
    idCaller: 'CLIENT-D',
    imageUrl: 'https://picsum.photos/seed/4/600/400',
    imageHint: 'product tech',
    category: 'Product',
  },
  {
    id: 'PROJ-005',
    name: 'Family Reunion Event',
    status: 'Pending by Customer',
    editorId: '4',
    assignDate: subDays(now, 15),
    deadline: subDays(now, 10),
    completionDate: subDays(now, 11),
    notes: 'Initial edits sent. Awaiting customer feedback on group photos.',
    idCaller: 'CLIENT-E',
    imageUrl: 'https://picsum.photos/seed/5/600/400',
    imageHint: 'family gathering',
    category: 'Event',
  },
  {
    id: 'PROJ-006',
    name: 'Delayed Birthday Party Edits',
    status: 'In Progress',
    editorId: '1',
    assignDate: subDays(now, 8),
    deadline: subDays(now, 2), // This project is delayed
    completionDate: null,
    notes: 'Client is waiting for these, please prioritize. Focus on candid shots.',
    idCaller: 'CLIENT-F',
    imageUrl: 'https://picsum.photos/seed/6/600/400',
    imageHint: 'birthday party',
    category: 'Event',
  },
  {
    id: 'PROJ-007',
    name: 'Architectural Shots',
    status: 'Done',
    editorId: '2',
    assignDate: subDays(now, 20),
    deadline: subDays(now, 15),
    completionDate: subDays(now, 14),
    notes: 'High contrast, black and white conversion.',
    idCaller: 'CLIENT-G',
    imageUrl: 'https://picsum.photos/seed/7/600/400',
    imageHint: 'architecture building',
    category: 'Corporate',
    picturesEdited: 80,
  },
  {
    id: 'PROJ-008',
    name: 'Pet Portrait Session',
    status: 'In Progress',
    editorId: '1',
    assignDate: subDays(now, 2),
    deadline: addDays(now, 3),
    completionDate: null,
    notes: 'Focus on capturing the dog\'s personality. Remove leashes where possible.',
    idCaller: 'CLIENT-H',
    imageUrl: 'https://picsum.photos/seed/8/600/400',
    imageHint: 'cute dog',
    category: 'Personal',
  },
  {
    id: 'PROJ-009',
    name: 'Fashion Lookbook',
    status: 'New',
    editorId: null,
    assignDate: null,
    deadline: addDays(now, 14),
    completionDate: null,
    notes: 'High-fashion edits. Skin retouching required.',
    idCaller: 'CLIENT-I',
    imageUrl: 'https://picsum.photos/seed/9/600/400',
    imageHint: 'fashion model',
    category: 'Product',
  },
  {
    id: 'PROJ-010',
    name: 'Delayed Done Project',
    status: 'Done',
    editorId: '3',
    assignDate: subDays(now, 12),
    deadline: subDays(now, 7),
    completionDate: subDays(now, 5), // Completed 2 days late
    notes: 'This project was completed after the deadline.',
    idCaller: 'CLIENT-J',
    imageUrl: 'https://picsum.photos/seed/10/600/400',
    imageHint: 'abstract art',
    category: 'Personal',
    picturesEdited: 200,
  },
];
